#pragma once

#define METADATA_NUMBER_OF_BLOCKS_LOC 0
#define METADATA_NUMBER_OF_BLOCKS_SIZE 4

#define METADATA_BLOCK_SIZE_LOC 4 
#define METADATA_BLOCK_SIZE_SIZE 4

#define METADATA_BLOCK_BITMAP_BLOCK_LOC 8
#define METADATA_BLOCK_BITMAP_BLOCK_SIZE 4

#define METADATA_BLOCK_BITMAP_NUMBER_OF_BLOCKS_LOC 12
#define METADATA_BLOCK_BITMAP_NUMBER_OF_BLOCKS_SIZE 2

#define METADATA_METADATA_NUMBER_OF_BLOCKS_LOC 14
#define METADATA_METADATA_NUMBER_OF_BLOCKS_SIZE 1

#define METADATA_START 0
#define METADATA_SIZE METADATA_NUMBER_OF_BLOCKS_SIZE+METADATA_BLOCK_SIZE_SIZE+METADATA_BLOCK_BITMAP_BLOCK_SIZE+METADATA_METADATA_NUMBER_OF_BLOCKS_SIZE+METADATA_BLOCK_BITMAP_NUMBER_OF_BLOCKS_SIZE

// task ids
#define TASK_GET_FREE_BLOCKS_ID 1

// getfreeblocks

#define TASK_GET_FREE_BLOCKS_CURRENT_BLOCK_LOC 0
#define TASK_GET_FREE_BLOCKS_CURRENT_BLOCK_SIZE 4

// task data requirements

#define TASK_GET_FREE_BLOCKS_DATA_SIZE TASK_GET_FREE_BLOCKS_CURRENT_BLOCK_SIZE+
