#pragma once

#define DISTINCT_NUMBER_OF_TASKS 3
#define MAXIMUM_NUMBER_OF_TASKS_ENQUEUEABLE 8

// schedule task state data
#define TASK_ID_SCHEDULE_TASK 0
#define TASK_STATE_SCHEDULE_TASK_LOC 0
#define TASK_STATE_SPACE_REQUIRED_SCHEDULE_TASK 1

#define TASK_STATE_SCHEDULE_TASK_LAST_ASSIGNED_TASK_LOC 0
#define TASK_STATE_SCHEDULE_TASK_LAST_ASSIGNED_TASK_SIZE 1

// get free blocks
#define TASK_ID_GET_FREE_BLOCKS 1
#define TASK_STATE_GET_FREE_BLOCKS_LOC 1
#define TASK_STATE_SPACE_REQUIRED_GET_FREE_BLOCKS 1

#define TASK_STATE_GET_FREE_BLOCKS_NEXT_BLOCK_TO_READ_LOC 0
#define TASK_STATE_GET_FREE_BLOCKS_NEXT_BLOCK_TO_READ_SIZE 1

// dummy task 
#define TASK_ID_DUMMY_TASK (DISTINCT_NUMBER_OF_TASKS-1)
