// SUPER BLOCK
#define SUPER_BLOCK_SIZE 1024

#define SUPER_BLOCK_INODE_SIZE_LOC 0x58
#define SUPER_BLOCK_INODES_PER_GROUP_LOC 0x28
#define SUPER_BLOCK_NUMBER_OF_BLOCKS_LOC 0x4
#define SUPER_BLOCK_NUMBER_OF_BLOCKS_HIGH_32_LOC 0x150
#define SUPER_BLOCK_NUMBER_OF_INODES_LOC 0x0
#define SUPER_BLOCK_BLOCK_SIZE_LOC 0x18
#define SUPER_BLOCK_BLOCKS_PER_GROUP_LOC 0x20
#define SUPER_BLOCK_GROUP_DESCRIPTOR_SIZE_LOC 0xFE
#define SUPER_BLOCK_FEATURES_INCOMPAT_LOC 0x60
#define SUPER_BLOCK_GROUPS_PER_FLEX 0x174
#define SUPER_BLOCK_NUMBER_OF_FREE_INODES_LOC 0x10


// INODE

#define INODE_I_BLOCK_SIZE 60

#define INODE_FILE_SIZE_HIGH_32_LOC 0x6c
#define INODE_FILE_SIZE_LOC 0x4
#define INODE_FILE_SIZE_SIZE 4

#define INODE_INODE_MODE_LOC 0x0
#define INODE_INODE_MODE_SIZE 2

#define INODE_FLAGS_LOC 0x20
#define INODE_FLAGS_SIZE 4

#define INODE_I_BLOCK_LOC 0x28
#define INODE_I_BLOCK_EXTENT_TREE_HEADER_SIZE 12
#define INODE_I_BLOCK_EXTENT_TREE_INTERNAL_NODE_SIZE 12
#define INODE_I_BLOCK_EXTENT_TREE_LEAF_NODE_SIZE 12

// FEATURES INCOMPAT FLAGS
#define FEATURE_INCOMPAT_64_BIT 0x80

// GROUP DESCRIPTOR

#define GROUP_DESCRIPTOR_INODE_TABLE_BLOCK_HIGH_32_LOC 0x28
#define GROUP_DESCRIPTOR_INODE_TABLE_BLOCK_LOC 0x8

#define GROUP_DESCRIPTOR_INODE_BITMAP_BLOCK_LOW_32_LOC 0x4
#define GROUP_DESCRIPTOR_INODE_BITMAP_BLOCK_LOW_32_SIZE 4

#define GROUP_DESCRIPTOR_INODE_BITMAP_BLOCK_HIGH_32_LOC 0x24
#define GROUP_DESCRIPTOR_INODE_BITMAP_BLOCK_HIGH_32_SIZE 4

#define GROUP_DESCRIPTOR_FLAGS_LOC 0x12
#define GROUP_DESCRIPTOR_FLAGS_SIZE 2

#define GROUP_DESCRIPTOR_FREE_INODE_COUNT_HIGH_16_LOC 0x2E
#define GROUP_DESCRIPTOR_FREE_INODE_COUNT_LOW_16_LOC 0xE
#define GROUP_DESCRIPTOR_FREE_INODE_COUNT_SIZE 2

#define GROUP_DESCRIPTOR_FREE_BLOCK_COUNT_HIGH_16_LOC 0x2C
#define GROUP_DESCRIPTOR_FREE_BLOCK_COUNT_LOW_16_LOC 0xC
#define GROUP_DESCRIPTOR_FREE_BLOCK_COUNT_SIZE 2

#define GROUP_DESCRIPTOR_BLOCK_BITMAP_HIGH_32_LOC 0x20
#define GROUP_DESCRIPTOR_BLOCK_BITMAP_LOW_32_LOC 0x0
#define GROUP_DESCRIPTOR_BLOCK_BITMAP_SIZE 4

#define GROUP_DESCRIPTOR_FLAG_INODE_UNINT 0x1
