// volume header

#define VOLUME_HEADER_SIZE 512

#define VOLUME_HEADER_BYTES_PER_SECTOR_LOC 11
#define VOLUME_HEADER_BYTES_PER_SECTOR_SIZE 2

#define VOLUME_HEADER_SECTORS_PER_CLUSTER_BLOCK_LOC 13
#define VOLUME_HEADER_SECTORS_PER_CLUSTER_BLOCK_SIZE 1

#define VOLUME_HEADER_MFT_CLUSTER_BLOCK_LOC 48
#define VOLUME_HEADER_MFT_CLUSTER_BLOCK_SIZE 8

#define VOLUME_HEADER_MFT_COPY_CLUSTER_BLOCK_LOC 56
#define VOLUME_HEADER_MFT_COPY_CLUSTER_BLOCK_SIZE 8

#define VOLUME_HEADER_MFT_ENTRY_SIZE_LOC 64
#define VOLUME_HEADER_MFT_ENTRY_SIZE_SIZE 1

#define VOLUME_HEADER_TOTAL_SECTORS_LOC 40
#define VOLUME_HEADER_TOTAL_SECTORS_SIZE 8

#define VOLUME_HEADER_INDEX_ENTRY_SIZE_LOC 68
#define VOLUME_HEADER_INDEX_ENTRY_SIZE_SIZE 1


// resident attribute data

#define MFT_RESIDENT_ATTRIBUTE_DATA_SIZE 8

#define MFT_RESIDENT_ATTRIBUTE_DATA_DATA_SIZE_LOC 0
#define MFT_RESIDENT_ATTRIBUTE_DATA_DATA_SIZE_SIZE 4 

#define MFT_RESIDENT_ATTRIBUTE_DATA_DATA_OFFSET_LOC 4
#define MFT_RESIDENT_ATTRIBUTE_DATA_DATA_OFFSET_SIZE 2 

// nonresident attribute data

#define COMPRESSION_UNIT_SIZE 0

#define MFT_NON_RESIDENT_ATTRIBUTE_DATA_SIZE 48
#define MFT_NON_RESIDENT_ATTRIBUTE_DATA_SIZE_COMP 56

#define MFT_NON_RESIDENT_ATTRIBUTE_DATA_FIRST_VCN_LOC 0
#define MFT_NON_RESIDENT_ATTRIBUTE_DATA_FIRST_VCN_SIZE 8 

#define MFT_NON_RESIDENT_ATTRIBUTE_DATA_LAST_VCN_LOC 8
#define MFT_NON_RESIDENT_ATTRIBUTE_DATA_LAST_VCN_SIZE 8 

#define MFT_NON_RESIDENT_ATTRIBUTE_DATA_DATA_RUNS_OFFSET_LOC 16
#define MFT_NON_RESIDENT_ATTRIBUTE_DATA_DATA_RUNS_OFFSET_SIZE 2 

#define MFT_NON_RESIDENT_ATTRIBUTE_DATA_ALLOCATED_DATA_SIZE_LOC 24
#define MFT_NON_RESIDENT_ATTRIBUTE_DATA_ALLOCATED_DATA_SIZE_SIZE 8 

#define MFT_NON_RESIDENT_ATTRIBUTE_DATA_DATA_SIZE_LOC 32
#define MFT_NON_RESIDENT_ATTRIBUTE_DATA_DATA_SIZE_SIZE 8

// MFT entry

#define MFT_ENTRY_HEADER_ATTRIBUTE_OFFSET_LOC 20
#define MFT_ENTRY_HEADER_ATTRIBUTE_OFFSET_SIZE 2


// attribute 

#define MFT_ATTRIBUTE_HEADER_SIZE 16

#define MFT_ATTRIBUTE_HEADER_ATTRIBUTE_SIZE_LOC 4
#define MFT_ATTRIBUTE_HEADER_ATTRIBUTE_SIZE_SIZE 4

#define MFT_ATTRIBUTE_HEADER_ATTRIBUTE_TYPE_LOC 0
#define MFT_ATTRIBUTE_HEADER_ATTRIBUTE_TYPE_SIZE 4

#define MFT_ATTRIBUTE_HEADER_NON_RESIDENT_FLAG_LOC 8
#define MFT_ATTRIBUTE_HEADER_NON_RESIDENT_FLAG_SIZE 1
