#define BUFFER_SIZE 4096
#define METADATA_SIZE 28

#define METADATA_VIRTUAL_DISK_SIZE_LOC 0 
#define METADATA_VIRTUAL_DISK_SIZE_SIZE 8

#define METADATA_NEXT_FREE_SPACE_POINTER_LOC 8
#define METADATA_NEXT_FREE_SPACE_POINTER_SIZE 8

#define METADATA_END_POINTER_DATA_POINTER_LOC 16
#define METADATA_END_POINTER_DATA_POINTER_SIZE 8

#define METADATA_NUMBER_OF_FILES_POINTER_LOC 24
#define METADATA_NUMBER_OF_FILES_POINTER_SIZE 4
